### ISSUE TITLE
Where is the Model?

### ISSUE THREAD

**Issue by musabgultekin** [HySonLab/ViDeBERTa#3]
Hello,

I noticed that the model code seems to be missing from the repository. I understand that this may limit the functionality and potential usefulness of the repository. Would it be possible to kindly provide an update on the status of the model code or if there are any plans to include it in the future? 

Thank you for your attention to this matter, and I appreciate your help in resolving this.

**Comment by DaoTranbk** [comment]
Thank @musabgultekin for your question.

We made the model checkpoints available at https://huggingface.co/Fsoft-AIC/. 
Please refer to this if you are interested in the model.

Cheers,
Cong Dao
